- name : Download the prometheus
  ansible.builtin.unarchive:
    src:  https://github.com/prometheus/prometheus/releases/download/{{ version }}/prometheus-2.54.1.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes