format_version: 10
pipelines:
  tools-tf-apply:
    group: Terraform
    materials:
      git-da613e5:
        git: https://github.com/iteration2-chaitu/tools-automation.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - APPLY:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
                - exec: {command: terraform, arguments: [ "init" ], run_if: passed}
                - exec: {command: terraform, arguments: [ "apply", "-auto-approve" ], run_if: passed}

#     - PROD:
#         fetch_materials: true
#         environment_variables:
#           env: prod
#         approval:
#           type: success
#         jobs:
#           terraform-apply:
#             tasks:
#             - exec: {command: terraform, arguments: [ "init", "-backend-config=env-prod/state.tfvars" ], run_if: passed}
#             - exec: {command: terraform, arguments: [ "apply", "-var-file=env-prod/main.tfvars", "-auto-approve" ], run_if: passed}